name: 'Build and test image to Registry'
description: 'Build and test image to Registry'
inputs:
  registry:
    description: 'Registry url'
    required: true
  namespace:
    description: 'Registry namespace'
    required: true
  password:
    description: 'Password'
    required: true
  username:
    description: 'Username'
    required: false
    default: "userdoesnotmatter"
  image_name:
    description: 'Image name'
    required: true
  tag:
    description: 'Image tags'
    required: true
  database_username:
    description: 'Database username'
    required: true
  database_password:
    description: 'Database password'
    required: true
  database_host:
    description: 'Database host'
    required: true
  push:
    description: 'Push image to registry'
    required: true
    default: "true"

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Clean tag
      uses: OpenSourcePolitics/clean-tag-action@master
      id: clean_tag
      with:
        tag: ${{ inputs.tag }}
    - uses: OpenSourcePolitics/build-and-push-images-action@master
      with:
        registry: ${{ inputs.registry }}
        namespace: ${{ inputs.namespace }}
        password: ${{ inputs.password }}
        username: ${{ inputs.username }}
        image_name: ${{ inputs.image_name }}
        tag: ${{ steps.clean_tag.outputs.tag }}
        push: ${{ inputs.push == 'true' }}
    - name: Test build
      shell: bash
      run: |
        docker run --rm -d --add-host=host.docker.internal:host-gateway -e DATABASE_USERNAME=${{inputs.database_username}} -e DATABASE_PASSWORD=${{inputs.database_password}} -e DATABASE_HOST=${{inputs.database_host}} -p 3000:3000 --name decidim-app ${{ inputs.registry }}/${{ inputs.namespace }}/${{ inputs.image_name }}:${{ steps.clean_tag.outputs.tag }}
        docker exec decidim-app bundle exec rake db:create db:migrate
        test_build.sh
